#include "Game.hpp"
#include <cassert>
#include <cstdio>
#include <cstdlib>

// unit tests generated by AI

int main() {
  Position mid{WORLD_W / 2, WORLD_H / 2};

  // standing still changes nothing
  Position p = simulate_step(mid, 0, 0);
  assert(p.x == mid.x && p.y == mid.y);

  // one second of straight movement covers exactly SPEED_PER_SEC
  p = mid;
  for (int i = 0; i < TICK_RATE_HZ; ++i)
    p = simulate_step(p, 1, 0);
  assert(p.x == mid.x + SPEED_PER_SEC && p.y == mid.y);

  // each direction
  assert(simulate_step(mid, -1, 0).x == mid.x - STEP);
  assert(simulate_step(mid, 0, 1).y == mid.y + STEP);
  assert(simulate_step(mid, 0, -1).y == mid.y - STEP);

  // diagonal is slower per axis, and never faster overall than straight
  p = simulate_step(mid, 1, 1);
  int ddx = p.x - mid.x, ddy = p.y - mid.y;
  assert(ddx == DIAG_STEP && ddy == DIAG_STEP);
  assert(ddx < STEP);
  assert(ddx * ddx + ddy * ddy <= STEP * STEP);

  // clamping at every edge and corner
  assert(simulate_step({0, 0}, -1, -1).x == 0);
  assert(simulate_step({0, 0}, -1, -1).y == 0);
  p = simulate_step({WORLD_W, WORLD_H}, 1, 1);
  assert(p.x == WORLD_W && p.y == WORLD_H);

  // lands exactly on the edge instead of overshooting
  p = simulate_step({WORLD_W - 3, 100}, 1, 0);
  assert(p.x == WORLD_W);

  // determinism: same start + same inputs = same result
  auto run = [](unsigned seed) {
    srand(seed);
    Position q = SPAWN;
    for (int i = 0; i < 5000; ++i)
      q = simulate_step(q, (int8_t)(rand() % 3 - 1), (int8_t)(rand() % 3 - 1));
    return q;
  };
  Position a = run(7), b = run(7);
  assert(a.x == b.x && a.y == b.y);

  // never leaves the world, whatever the inputs
  srand(1);
  p = SPAWN;
  for (int i = 0; i < 200000; ++i) {
    static int8_t dx = 0, dy = 0;
    if (i % 500 == 0) {
      dx = (int8_t)(rand() % 3 - 1);
      dy = (int8_t)(rand() % 3 - 1);
    }
    p = simulate_step(p, dx, dy);
    assert(p.x >= 0 && p.x <= WORLD_W && p.y >= 0 && p.y <= WORLD_H);
  }

  puts("game tests passed");
}